language: ruby
rvm: 2.0.0
before_script:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$GH_TOKEN" ] && rake setup'
script: rake build
after_success:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$GH_TOKEN" ] && rake publish'

env:
  global:
    - secure: "LIGAV/YyUGL3oMu+n30w58Utjs4uwXFv1Eh0RFuesLsaQDtuzkW++9ok5hX0BwIZONtZAItCdQkFl0kvRHA35ioIrL4Q3DheG/zQWIOUoAD2lyW4nFX+AdtrxTzho/YWKJd//751FQmPpgaQA/oMkuYHCDv3aPOhTFHMT4yhKgo="
    - GIT_COMMITTER_NAME=travis
    - GIT_COMMITTER_EMAIL=travis@example.com
    - GIT_AUTHOR_NAME=travis
    - GIT_AUTHOR_EMAIL=travis@example.com

