language: ruby
rvm: 2.0.0
before_script:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$GH_TOKEN" ] && rake setup'
script: rake build
after_success:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$GH_TOKEN" ] && rake publish'

env:
  global:
    - secure: "PqagaSNekEN+LoFzuIj5x0xqkIL9OqlfJsZOqV+hrH18P6LN8OF4DmjuowU9Mm84KSewoTxRQ/KBF/PWOTNfuvJ0Kigv+3nNWMeZWBykTpfKq5+8q6blqHbPWNAxtdKrn69nYMRm+0/C+PG5iYuQnRCu8Jm967gBjinbbvPxmPY="
    - GIT_COMMITTER_NAME=travis
    - GIT_COMMITTER_EMAIL=travis@example.com
    - GIT_AUTHOR_NAME=travis
    - GIT_AUTHOR_EMAIL=travis@example.com

